name = "Naloga3"
uuid = "cc2d6ffb-4faa-4d8c-874c-4f3ce0e498cf"
authors = ["tinakindrb"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
